### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#15]
As a user,
After authenticating (either via login or signup),
I am redirected to the dashboard page,
Where I see:
- [x] A "Profile" section on the left side of the page (stories #16, #19)
- [x] A "Medications list" section below the Profile section (#20)
- [x] A "Log a Symptom" section (story #17)
- [x] A "Recent Logs" section (story #18)
- [x] A "logout" button in the top left corner (story #21)

**Implementation details:**
- [x] mock `current_user`
- [x] create `DashboardController` and `#index` action
- [X] sad path: can't access the dashboard without logging in
